### ISSUE TITLE
Hi Moulaye!

### ISSUE THREAD

**Issue by matheo** [moolsbytheway/mf-dynamic-form#3]
I've found your repo in [ngx.tools](https://www.ngx.tools/#/search?q=dynamic%20forms)
and I want to invite you to join a new open-source library that we're doing to support strong dynamic-forms.

I've made a stepper-form kinda similar to the one you have as demo:
https://myndpm.github.io/open-source/#/demos/dyn-forms/stepper-form

Instead having to support a complete platform,
we can join efforts to accomplish your roadmap! :+1: 
all I ask you is to join our [discussions](https://github.com/myndpm/open-source/discussions) and talk about the stuff you want implemented.

If you like this idea and if you don't mind, please present yourself in the [Welcome!](https://github.com/myndpm/open-source/discussions/1) thread and join any topic of your interest.
I see that you're adding i18n support, we could work on some solution based on `@ngx-translate` as I already support `Reactive parameters` and we can build a reactive set of parameters depending on the language :wink: 

Looking forward to hear from you!
Best regards

**Comment by moolsbytheway** [comment]
Hello @matheo
Thank you for reaching out.
